### ISSUE TITLE
VueScan don't remember my license.

### ISSUE THREAD

**Issue by andresimi** [flathub/com.hamrick.VueScan#2]
Hi, I was having problems with the scanner from HP LaserJet Pro MFP m125nw in Fedora 29 and tried hplip forum without an [answer](https://answers.launchpad.net/hplip/+question/677336) (until this momment). I was in a hurry and was glad to find VueScan in flathub repository and that it could solve the problem. So, I bought the license.

However, everytime I enter the program I have to retype the license info. I sent an e-mail to the developer of the program who could only provide this tip: "Is the HOME environment variable set up to point to the folder where .vuescanrc gets created?".

I tried with the code below, but steel not suceed.
flatpak run com.hamrick.VueScan/x86_64/stable --env=PATH=~/.var/app/com.hamrick.VueScan/

Could you help me?

**Comment by FakeShemp** [comment]
The problem most likely is a garbage file created in the `~/.var/app/com.hamrick.VueScan` (or equivalent) path. You can try to delete the `.vuescanrc` folder/file in there after starting the app and then entering the registration info. That should solve the problem for you.

@TingPing Is there a way to tell flatpak to _not_ create a file or folder when using `--persist`. VueScan saves its license file (`.vuescanrc`) directly in the HOME folder, and when using `--persist=.vuescanrc` an empty folder named `.vuescanrc` is created instead of the file the app needs.

**Comment by andresimi** [comment]
Hi, thanks for trying to help. I tried what you suggested with no success. The .vuescanrc is empty and seems to have no file saved after the input of the license.

**Comment by FakeShemp** [comment]
Okay, I think I've managed to track down the issue. As soon as the buildbot finishes, an update should be available. However, one issue still remains, you need to create an empty file in your home directory named `.vuescanrc` before entering your licence, but you should have it activated after that.

**Comment by TingPing** [comment]
> @TingPing Is there a way to tell flatpak to not create a file or folder when using --persist. VueScan saves its license file (.vuescanrc) directly in the HOME folder, and when using --persist=.vuescanrc an empty folder named .vuescanrc is created instead of the file the app needs.

This is literally how `--persist` works, so I'm very confused.

**Comment by FakeShemp** [comment]
Yes, I understand that now. Hence persist cannot be used for vuescan, unless you allow something dumb like `--persist=~`

**Comment by TingPing** [comment]
Hmm, It might not be that dumb.

**Comment by andresimi** [comment]
Hi, any news on this? I am facing the same problem... Thank you

**Comment by FakeShemp** [comment]
@andresimi It hasn't been solved but you can launch it with `flatpak run com.hamrick.VueScan --filesystem=home` and enter your licence info. It should unlock automagically from there on with regular launches.

**Comment by andresimi** [comment]
Hi @FakeShemp , thank you for helping. 
For the record, I tried 
> flatpak run com.hamrick.VueScan --filesystem=home

and

> flatpak run com.hamrick.VueScan --filesystem=/home/mylogin

without success.

**Comment by mabushey** [comment]
You need to buy it again. Ed Hamrick lies about the "lifetime upgrades".
