### ISSUE TITLE
Use appdata from deb or rpm

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.hamrick.VueScan#39]
VueScan now has a deb and rpm download which comes with appdata and desktop files. Use those as a base for the flatpak instead.

https://www.hamrick.com/alternate-versions.html

**Comment by TingPing** [comment]
Upstream appdata has to be patched to be valid.

**Comment by FakeShemp** [comment]
The needed data is actually licensed CC0, so I think can just update the ones in the repo with the data I need instead.

**Comment by TingPing** [comment]
Since upstream is shipping appdata at all it would be ideal to start a discussion with them about it.
